import { Geist, Geist_Mono } from "next/font/google";
import AppPaddingWrapper from "@/components/layout/AppPaddingWrapper";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${geistSans.variable} ${geistMono.variable} antialiased    bg-[#E8E8E8]`}>
        <AppPaddingWrapper>
          {children}
        </AppPaddingWrapper>
       
       
      </body>
    </html>
  );
}
